os: linux

language: go

go:
    - "1.11"

python:
    - "2.7"
    - "3.5"

addons:
  apt:
    packages:
      - flawfinder
      - squashfs-tools
      - uuid-dev
      - libuuid1
      - libffi-dev
      - libssl-dev
      - libssl1.0.0
      - libarchive-dev
      - libgpgme11-dev
      - libseccomp-dev
  homebrew:
    packages:
      - squashfs
    update: true


sudo: required
#dist: trusty


matrix:
  include:
    - python: "2.6"
    - python: "3.5"

before_install:
  - sudo chmod u+x .travis/*.sh
  - /bin/bash .travis/setup.sh

install:
  - # override

script:
                               # recipe
  - /bin/bash .travis/build.sh Singularity

                               # recipe with tag
  #- /bin/bash .travis/build.sh --tag sneeze Singularity.tag

  # Examples with upload to storage clients defined by sregistry
  # https://singularityhub.github.io/sregistry-cli/clients
  # Environment variables must be defined in CI encrypted secrets/settings

  #- /bin/bash .travis/build.sh --uri collection/container --tag tacos --cli google-storage Singularity
  #- /bin/bash .travis/build.sh --uri collection/container --cli google-drive Singularity
  #- /bin/bash .travis/build.sh --uri collection/container --cli globus Singularity
  #- /bin/bash .travis/build.sh --uri collection/container --cli registry Singularity
